### ISSUE TITLE
How to use AOT compilation with `typebox`?

### ISSUE THREAD

**Issue by samchon** [sinclairzx81/runtime-type-benchmarks#4]
You've made an interesting project. 

Looking at benchmark result picture, I've something to ask you. How did you AOT compile through `typebox`?

**Comment by sinclairzx81** [comment]
Heya,

TypeBox has had the ability to do AOT since the compiler was added to the library. It's just that TypeBox expects end users to implement their own mechanisms for writing the code to disk (presumably via some cli tooling process). The `.Code()` function was added to allow end users the ability to precompile validation logic in constrained `content-security-policy` environments where `eval()` or 'Function' is restricted.

### Code Generation

As you've probably seen before

```typescript
const code = TypeCompiler.Compile(Type.Object({
  x: Type.Number(),
  y: Type.Number(),
  z: Type.Number()
})).Code()

// return function check(value) {
//   return (
//     (typeof value === 'object' && value !== null && !Array.isArray(value)) &&
//     (typeof value.x === 'number' && !isNaN(value.x)) &&
//     (typeof value.y === 'number' && !isNaN(value.y)) &&
//     (typeof value.z === 'number' && !isNaN(value.z))
//  )
// }
```
### Benchmarks

All the benchmarks in this project are generated from TypeBox schematics. During the generation pass for the `typebox_aot` benchmark, I use the code above to inline the validation logic which is later compiled by TypeScript when the benchmark is run.

```typescript
yield `Cases.Benchmark(Cases.${schema.$id}, iterations, results, () => { 
  ${TypeCompiler.Compile(schema).Code()} 
})`
```
Generation Script can be found here https://github.com/sinclairzx81/runtime-type-benchmarks/blob/dataset/benchmark/validators/typebox_aot/build.ts#L28-L30

Hope that helps!
S

**Comment by sinclairzx81** [comment]
Will close this issue off. Cheers
